export const players = [
  {
    id: 1,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 2,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 3,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 4,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 5,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 6,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 7,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 8,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 9,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 10,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 11,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 12,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
  {
    id: 13,
    name: "Mbappe",
    img: "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/12/19/247181.jpg",
    desc: "Transfer Live: Chlesea in talks over Kimpenbe transfer",
    watch: "10h",
    msg: "23",
  },
];
